package basictests;

/**
 * Created by Andrii.Fiedosieiev on 7/25/2017.
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class FibSum {
    public static void main(String[] args) {
        int fib = 1;
        int fib1 = 2;
        int quiantity = 44;
        int sum = 0;

        for (int i = 0; i < quiantity; i++) {
            if ((fib % 2 == 0 && fib <= 4000000)) {
                System.out.println(fib);
                sum+=fib;

            }
            fib = fib + fib1;
            fib1 = fib - fib1;


        }
        System.out.println(sum);
    }
}
